// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puunmvbkvssxuzbvkthm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dW5tdmJrdnNzeHV6YnZrdGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTYwMDAsImV4cCI6MjA2MjQzMjAwMH0.ICpWUKL0uSmETrRlW4WR7wHK_5pHCDxXDbWig4t7WJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);